### ISSUE TITLE
plakar agent task stops panics

### ISSUE THREAD

**Issue by brmzkw** [PlakarKorp/plakar#1128]
I'm not sure it happens all the time, or if I'm running several run/start in a row.

```
$ plakar agent tasks stop
Stopping agent scheduler... (may take some time)
done !
$ panic: pebble: closed

goroutine 902195 [running]:
github.com/cockroachdb/pebble/v2.(*DB).applyInternal(0x1400031e180?, 0x14012ffe4b0?, 0x4a?, 0xa8?)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/cockroachdb/pebble/v2/db.go:826 +0x3b4
github.com/cockroachdb/pebble/v2.(*DB).Apply(...)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/cockroachdb/pebble/v2/db.go:801
github.com/cockroachdb/pebble/v2.(*DB).Set(0x14000dce908, {0x14012ffe4b0, 0x4a, 0x4a}, {0x107037a80, 0x0, 0x0}, 0x107037aa3)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/cockroachdb/pebble/v2/db.go:638 +0x80
github.com/PlakarKorp/kloset/caching.(*PebbleCache).put(0x140023b3228, {0x1059531e6?, 0x14007e27818?}, {0x14005048300, 0x40}, {0x107037a80, 0x0, 0x0})
    /Users/niluje/dev/plakar/plakar/vendor/github.com/PlakarKorp/kloset/caching/pebble.go:46 +0xd0
github.com/PlakarKorp/kloset/caching.(*CheckCache).PutChunkStatus(0x14013948b20, {0x52, 0x25, 0xa2, 0x43, 0x50, 0x7a, 0x6, 0x9b, 0xf9, ...}, ...)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/PlakarKorp/kloset/caching/check.go:73 +0x98
github.com/PlakarKorp/kloset/snapshot.checkChunk(0x14013948b80, 0x14005048180, {0x1062ee260, 0x140056bd500}, 0x0)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/PlakarKorp/kloset/snapshot/check.go:83 +0x63c
github.com/PlakarKorp/kloset/snapshot.checkObject(0x14013948b80, 0x14005349040, 0x0)
    /Users/niluje/dev/plakar/plakar/vendor/github.com/PlakarKorp/kloset/snapshot/check.go:115 +0x3b0
github.com/PlakarKorp/kloset/snapshot.checkEntry.func1()
    /Users/niluje/dev/plakar/plakar/vendor/github.com/PlakarKorp/kloset/snapshot/check.go:169 +0x50
golang.org/x/sync/errgroup.(*Group).Go.func1()
    /Users/niluje/dev/plakar/plakar/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 437852
    /Users/niluje/dev/plakar/plakar/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x98

```

Configuration file used:

```yaml
agent:
  tasks:
    - name: plakar
      repository: /var/backups

      backup:
        path: /Users/niluje/dev/plakar/plakar
        interval: 5s
        check: true

      check:
        - interval: 1s
          path: /
          latest: true
```
