### ISSUE TITLE
summaries are broken, snapshots no longer reports size

### ISSUE THREAD

**Issue by poolpOrg** [PlakarKorp/plakar#361]
recent btree updates broke the summaries:

```
Summary:
 - Directories: 0
 - Files: 0
 - Symlinks: 0
 - Devices: 0
 - Pipes: 0
 - Sockets: 0
 - Setuid: 0
 - Setgid: 0
 - Sticky: 0
 - Objects: 0
 - Chunks: 0
 - MinSize: 0 B (0 bytes)
 - MaxSize: 0 B (0 bytes)
 - Size: 0 B (0 bytes)
 - MinModTime: 1970-01-01 01:00:00 +0100 CET
 - MaxModTime: 1970-01-01 01:00:00 +0100 CET
 - MinEntropy: 0.000000
 - MaxEntropy: 0.000000
 - HiEntropy: 0
 - LoEntropy: 0
 - MIMEAudio: 0
 - MIMEVideo: 0
 - MIMEImage: 0
 - MIMEText: 0
 - MIMEApplication: 0
 - MIMEOther: 0
 - Errors: 0
```
