### ISSUE TITLE
Plakar complains about a missing access_key (Backblaze B2) only when the agent is running

### ISSUE THREAD

**Issue by ncartron** [PlakarKorp/plakar#713]
**Describe the bug**
Plakar is configured with a Backblaze B2 target.
When ran agentless, it works.
If I start the agent, I'm getting:

```
√ ~ % plakar at @b2-nico backup ls
plakar: missing access_key
Failed to open storage: missing access_key
```

**To Reproduce**
Running on Plakar 1.0.0-beta9

Configuration:

```
default-repo: ""
repositories:
    b2-nico:
        access_key: XXX
        location: s3://s3.us-west-000.backblazeb2.com/plakar-b2
        secret_access_key: YYY
remotes: {}

```

**Expected behavior**
Plakar commands should work with the agent running, but they are not/

**Screenshots**
